"""
Manual test to debug PLACEMENT tournament creation issue
"""
import requests
import json

# Login
login_resp = requests.post('http://localhost:8000/api/v1/auth/login',
                           json={'email': 'admin@lfa.com', 'password': 'admin123'})
token = login_resp.json()['access_token']
headers = {'Authorization': f'Bearer {token}'}

print("✅ Logged in successfully\n")

# Create PLACEMENT tournament via sandbox/run-test
print("📝 Creating PLACEMENT tournament via /api/v1/sandbox/run-test...")
create_payload = {
    "tournament_type": "league",
    "skills_to_test": ["passing"],
    "player_count": 8,
    "test_config": {
        "performance_variation": "MEDIUM",
        "ranking_distribution": "NORMAL",
        "game_config_overrides": {
            "scoring_mode": "INDIVIDUAL",
            "individual_config": {
                "number_of_rounds": 1,
                "scoring_type": "PLACEMENT",
                "ranking_direction": "ASC",
                "measurement_unit": None
            }
        }
    }
}

create_resp = requests.post('http://localhost:8000/api/v1/sandbox/run-test',
                           headers=headers, json=create_payload)

print(f"Status: {create_resp.status_code}")

if create_resp.status_code == 200:
    result = create_resp.json()
    tournament_id = result['tournament']['id']
    print(f"✅ Tournament created! ID: {tournament_id}")
    print(f"   Tournament status: {result['tournament'].get('tournament_status')}")

    # Check if sessions were auto-generated
    print(f"\n📋 Checking tournament_configurations...")
    config_resp = requests.get(f'http://localhost:8000/api/v1/tournaments/{tournament_id}',
                              headers=headers)
    if config_resp.status_code == 200:
        tournament = config_resp.json()
        sessions_generated = tournament.get('sessions_generated', False)
        print(f"   sessions_generated: {sessions_generated}")

    # Try to generate sessions (this is what Streamlit does)
    print(f"\n🔧 Attempting to generate sessions (like Streamlit does)...")
    generate_resp = requests.post(
        f'http://localhost:8000/api/v1/tournaments/{tournament_id}/generate-sessions',
        headers=headers,
        json={"parallel_fields": 1, "session_duration_minutes": 90, "break_minutes": 15}
    )

    print(f"Status: {generate_resp.status_code}")
    if generate_resp.status_code == 400:
        print(f"❌ ERROR: {generate_resp.json()}")
        print("\n🎯 ROOT CAUSE: Sessions already generated by /sandbox/run-test!")
        print("   Streamlit workflow tries to generate again and fails.")
    elif generate_resp.status_code == 200:
        print(f"✅ Sessions generated: {generate_resp.json()}")
    else:
        print(f"⚠️  Unexpected response: {generate_resp.text}")

else:
    print(f"❌ Tournament creation failed: {create_resp.text}")
