"""
Auto-generated smoke tests for health domain
Generated by tools/generate_api_tests.py

⚠️  DO NOT EDIT MANUALLY - Regenerate using:
    python tools/generate_api_tests.py --scan-api app/api --output tests/integration/api_smoke/
"""

import pytest
from fastapi.testclient import TestClient


class TestHealthSmoke:
    """Smoke tests for health API endpoints"""


    # ── GET /latest-report ────────────────────────────

    def test_get_latest_health_report_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /latest-report
        Source: app/api/api_v1/endpoints/health.py:get_latest_health_report
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/latest-report", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 404], (
            f"GET /latest-report failed: {response.status_code} "
            f"{response.text}"
        )

    def test_get_latest_health_report_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /latest-report requires authentication
        """
        
        response = api_client.get("/latest-report")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [401, 403], (
            f"GET /latest-report should require auth: {response.status_code}"
        )

    def test_get_health_metrics_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /metrics
        Source: app/api/api_v1/endpoints/health.py:get_health_metrics
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/metrics", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 404], (
            f"GET /metrics failed: {response.status_code} "
            f"{response.text}"
        )

    def test_get_health_metrics_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /metrics requires authentication
        """
        
        response = api_client.get("/metrics")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [401, 403], (
            f"GET /metrics should require auth: {response.status_code}"
        )

    def test_get_health_status_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /status
        Source: app/api/api_v1/endpoints/health.py:get_health_status
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/status", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 404], (
            f"GET /status failed: {response.status_code} "
            f"{response.text}"
        )

    def test_get_health_status_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /status requires authentication
        """
        
        response = api_client.get("/status")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [401, 403], (
            f"GET /status should require auth: {response.status_code}"
        )

    def test_get_current_violations_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /violations
        Source: app/api/api_v1/endpoints/health.py:get_current_violations
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/violations", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 404], (
            f"GET /violations failed: {response.status_code} "
            f"{response.text}"
        )

    def test_get_current_violations_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /violations requires authentication
        """
        
        response = api_client.get("/violations")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [401, 403], (
            f"GET /violations should require auth: {response.status_code}"
        )

    def test_run_health_check_now_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: POST /check-now
        Source: app/api/api_v1/endpoints/health.py:run_health_check_now
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        # TODO: Add realistic payload for /check-now
        payload = {}
        response = api_client.post("/check-now", json=payload, headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 404], (
            f"POST /check-now failed: {response.status_code} "
            f"{response.text}"
        )

    def test_run_health_check_now_auth_required(self, api_client: TestClient):
        """
        Auth validation: POST /check-now requires authentication
        """
        
        response = api_client.post("/check-now", json={})
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [401, 403], (
            f"POST /check-now should require auth: {response.status_code}"
        )

    @pytest.mark.skip(reason="Input validation requires domain-specific payloads")
    def test_run_health_check_now_input_validation(self, api_client: TestClient, admin_token: str):
        """
        Input validation: POST /check-now validates request data
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        # Invalid payload (empty or malformed)
        invalid_payload = {"invalid_field": "invalid_value"}
        response = api_client.post(
            "/check-now",
            json=invalid_payload,
            headers=headers
        )

        # Should return 422 Unprocessable Entity for validation errors
        assert response.status_code in [400, 422], (
            f"POST /check-now should validate input: {response.status_code}"
        )
        

