"""
Auto-generated smoke tests for students domain
Generated by tools/generate_api_tests.py

⚠️  DO NOT EDIT MANUALLY - Regenerate using:
    python tools/generate_api_tests.py --scan-api app/api --output tests/integration/api_smoke/
"""

import pytest
from fastapi.testclient import TestClient


class TestStudentsSmoke:
    """Smoke tests for students API endpoints"""


    # ── GET /dashboard/achievements ────────────────────────────

    def test_get_achievements_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /dashboard/achievements
        Source: app/api/api_v1/endpoints/students.py:get_achievements
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/dashboard/achievements", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 404], (
            f"GET /dashboard/achievements failed: {response.status_code} "
            f"{response.text}"
        )

    def test_get_achievements_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /dashboard/achievements requires authentication
        """
        
        response = api_client.get("/dashboard/achievements")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [401, 403], (
            f"GET /dashboard/achievements should require auth: {response.status_code}"
        )

    def test_get_daily_challenge_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /dashboard/daily-challenge
        Source: app/api/api_v1/endpoints/students.py:get_daily_challenge
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/dashboard/daily-challenge", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 404], (
            f"GET /dashboard/daily-challenge failed: {response.status_code} "
            f"{response.text}"
        )

    def test_get_daily_challenge_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /dashboard/daily-challenge requires authentication
        """
        
        response = api_client.get("/dashboard/daily-challenge")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [401, 403], (
            f"GET /dashboard/daily-challenge should require auth: {response.status_code}"
        )

    def test_get_semester_progress_happy_path(self, api_client: TestClient, admin_token: str):
        """
        Happy path: GET /dashboard/semester-progress
        Source: app/api/api_v1/endpoints/students.py:get_semester_progress
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/dashboard/semester-progress", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 404], (
            f"GET /dashboard/semester-progress failed: {response.status_code} "
            f"{response.text}"
        )

    def test_get_semester_progress_auth_required(self, api_client: TestClient):
        """
        Auth validation: GET /dashboard/semester-progress requires authentication
        """
        
        response = api_client.get("/dashboard/semester-progress")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [401, 403], (
            f"GET /dashboard/semester-progress should require auth: {response.status_code}"
        )

