"""
Auto-generated smoke tests for dashboard domain
Generated by tools/generate_api_tests.py

⚠️  DO NOT EDIT MANUALLY - Regenerate using:
    python tools/generate_api_tests.py --scan-api app/api --output tests/integration/api_smoke/
"""

import pytest
from fastapi.testclient import TestClient


class TestDashboardSmoke:
    """Smoke tests for dashboard API endpoints"""


    # ── GET /api/v1/dashboard ────────────────────────────

    def test_unknown_happy_path(
        self,
        api_client: TestClient,
        admin_token: str,
    ):
        """
        Happy path: GET /api/v1/dashboard
        Source: app/api/web_routes/dashboard.py:unknown
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/api/v1/dashboard/dashboard", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 404], (
            f"GET /api/v1/dashboard failed: {response.status_code} "
            f"{response.text}"
        )

    def test_unknown_auth_required(
        self,
        api_client: TestClient,
    ):
        """
        Auth validation: GET /api/v1/dashboard requires authentication
        """
        
        response = api_client.get("/api/v1/dashboard/dashboard")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [401, 403], (
            f"GET /api/v1/dashboard should require auth: {response.status_code}"
        )

    @pytest.mark.skip(reason="Input validation requires domain-specific payloads")
    def test_unknown_input_validation(
        self,
        api_client: TestClient,
        admin_token: str,
    ):
        """
        Input validation: GET /api/v1/dashboard validates request data
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        # GET/DELETE don't typically have input validation
        pytest.skip("No input validation for GET endpoints")
        


    # ── GET /api/v1/dashboard-fresh ────────────────────────────

    def test_dashboard_happy_path(
        self,
        api_client: TestClient,
        admin_token: str,
    ):
        """
        Happy path: GET /api/v1/dashboard-fresh
        Source: app/api/web_routes/dashboard.py:dashboard
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get("/api/v1/dashboard/dashboard-fresh", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 404], (
            f"GET /api/v1/dashboard-fresh failed: {response.status_code} "
            f"{response.text}"
        )

    def test_dashboard_auth_required(
        self,
        api_client: TestClient,
    ):
        """
        Auth validation: GET /api/v1/dashboard-fresh requires authentication
        """
        
        response = api_client.get("/api/v1/dashboard/dashboard-fresh")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [401, 403], (
            f"GET /api/v1/dashboard-fresh should require auth: {response.status_code}"
        )

    @pytest.mark.skip(reason="Input validation requires domain-specific payloads")
    def test_dashboard_input_validation(
        self,
        api_client: TestClient,
        admin_token: str,
    ):
        """
        Input validation: GET /api/v1/dashboard-fresh validates request data
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        # GET/DELETE don't typically have input validation
        pytest.skip("No input validation for GET endpoints")
        


    # ── GET /api/v1/dashboard/{spec_type} ────────────────────────────

    def test_spec_dashboard_happy_path(
        self,
        api_client: TestClient,
        admin_token: str,
        test_tournament,
    ):
        """
        Happy path: GET /api/v1/dashboard/{spec_type}
        Source: app/api/web_routes/dashboard.py:spec_dashboard
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        response = api_client.get(f"/api/v1/dashboard/dashboard/{test_tournament["spec_type"]}", headers=headers)
        

        # Accept 200, 201, 404 (if resource doesn't exist in test DB)
        assert response.status_code in [200, 201, 404], (
            f"GET /api/v1/dashboard/{spec_type} failed: {response.status_code} "
            f"{response.text}"
        )

    def test_spec_dashboard_auth_required(
        self,
        api_client: TestClient,
        test_tournament,
    ):
        """
        Auth validation: GET /api/v1/dashboard/{spec_type} requires authentication
        """
        
        response = api_client.get(f"/api/v1/dashboard/dashboard/{test_tournament["spec_type"]}")
        

        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in [401, 403], (
            f"GET /api/v1/dashboard/{spec_type} should require auth: {response.status_code}"
        )

    @pytest.mark.skip(reason="Input validation requires domain-specific payloads")
    def test_spec_dashboard_input_validation(
        self,
        api_client: TestClient,
        admin_token: str,
        test_tournament,
    ):
        """
        Input validation: GET /api/v1/dashboard/{spec_type} validates request data
        """
        headers = {"Authorization": f"Bearer {admin_token}"}

        
        # GET/DELETE don't typically have input validation
        pytest.skip("No input validation for GET endpoints")
        

