"""Add instructor_rating, session_quality, would_recommend to feedback

Revision ID: 2df11d5f7ff0
Revises: 3c8f68b69142
Create Date: 2025-09-06 13:33:47.233467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df11d5f7ff0'
down_revision = '3c8f68b69142'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('instructor_rating', sa.Float(), nullable=True))
    op.add_column('feedback', sa.Column('session_quality', sa.Float(), nullable=True))
    op.add_column('feedback', sa.Column('would_recommend', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'would_recommend')
    op.drop_column('feedback', 'session_quality')
    op.drop_column('feedback', 'instructor_rating')
    # ### end Alembic commands ###