"""Add onboarding and profile fields to User model

Revision ID: 938b083601ad
Revises: ab3db1e041b8
Create Date: 2025-09-13 17:19:31.394780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938b083601ad'
down_revision = 'ab3db1e041b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('emergency_contact', sa.String(), nullable=True))
    op.add_column('users', sa.Column('emergency_phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('medical_notes', sa.String(), nullable=True))
    op.add_column('users', sa.Column('interests', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'interests')
    op.drop_column('users', 'medical_notes')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'emergency_phone')
    op.drop_column('users', 'emergency_contact')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'onboarding_completed')
    # ### end Alembic commands ###